### ISSUE TITLE
Database file is missing

### ISSUE THREAD

**Issue by xDropEm** [alexandra-valkova/PhonebookMVC#1]
Hey! can u plz share your database file too. Coz I am not able to perform database operations

**Comment by alexandra-valkova** [comment]
> Hey! can u plz share your database file too. Coz I am not able to perform database operations

Hello @xDropEm 👋🏻 thanks for raising this issue, I have [added the migration file that was missing, fixed the Seed method](https://github.com/alexandra-valkova/PhonebookMVC/commit/d97257db7feef6b7d8f71bbc7cd8abb63424b0b6), now there should be no issues initializing and using the database 🗃️
