### ISSUE TITLE
Can't get the application to work on IIS

### ISSUE THREAD

**Issue by Gnu3n** [alexandra-valkova/PhonebookMVC#2]
After successfully deploying it to a Windows Server 2019 IIS i can't seem to get the site to load, stating that no default document can be found.

What am i missing?

**Comment by alexandra-valkova** [comment]
> After successfully deploying it to a Windows Server 2019 IIS i can't seem to get the site to load, stating that no default document can be found.
> 
> What am i missing?

Hello @Gnu3n 👋🏻 I'm sorry you've encountered this issue, but I cannot replicate it currently, maybe it has been resolved in the meantime. Thanks nonetheless.
